/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import java.awt.Color;
import javax.swing.ImageIcon;
/**
 *
 * @author Administrador
 */
public class MenuDashboard2 extends javax.swing.JFrame {

    /**
     * Creates new form MenuDashboard2
     */
    public MenuDashboard2() {
        initComponents();
        this.setLocationRelativeTo(this);
        
        JPLogin.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JPLogin = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        NameEmpresa = new javax.swing.JLabel();
        TitleEmpresa = new javax.swing.JLabel();
        User1 = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        Separator1 = new javax.swing.JSeparator();
        User = new javax.swing.JLabel();
        Pass = new javax.swing.JPasswordField();
        Separator = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        checkbox1 = new java.awt.Checkbox();
        jButton4 = new javax.swing.JButton();
        ingresar = new javax.swing.JButton();
        BackGround = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        JPPrincipal = new javax.swing.JPanel();
        JPCabecera = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        JPMenu = new javax.swing.JPanel();
        JPBienvenida = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JPCajero = new javax.swing.JPanel();
        JPBotonesCajero = new javax.swing.JPanel();
        btnPanelRegistrarCliente1 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnPanelRegistrarCliente = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnPanelRegistrarCliente3 = new javax.swing.JToggleButton();
        btnPanelRegistrarCliente2 = new javax.swing.JToggleButton();
        JPAdministrador = new javax.swing.JPanel();
        JPBotonesAdmin = new javax.swing.JPanel();
        btnPanelRegistrarCliente5 = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        btnPanelRegistrarCliente4 = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        btnPanelRegistrarCliente6 = new javax.swing.JToggleButton();
        btnPanelRegistrarCliente7 = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPLogin.setBackground(new java.awt.Color(255, 255, 255));
        JPLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        NameEmpresa.setFont(new java.awt.Font("TrocaderoProW00-Cursive", 0, 48)); // NOI18N
        NameEmpresa.setText("CasinoCraft");

        TitleEmpresa.setFont(new java.awt.Font("Fira Code Medium", 0, 18)); // NOI18N
        TitleEmpresa.setText("Welcome to CasinoCraft");

        User1.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        User1.setText("User");

        Usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Usuario.setForeground(new java.awt.Color(204, 204, 204));
        Usuario.setText("Ingrese su usuario");
        Usuario.setToolTipText("");
        Usuario.setActionCommand("<Not Set>");
        Usuario.setBorder(null);
        Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UsuarioMousePressed(evt);
            }
        });
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });

        User.setFont(new java.awt.Font("Fira Code", 0, 18)); // NOI18N
        User.setText("Password");

        Pass.setForeground(new java.awt.Color(204, 204, 204));
        Pass.setText("**********");
        Pass.setBorder(null);
        Pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PassMousePressed(evt);
            }
        });
        Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassActionPerformed(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Forgot your Password?");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        checkbox1.setLabel("Remember me");

        jButton4.setFont(new java.awt.Font("Fira Code Medium", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setText("X");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        ingresar.setBackground(new java.awt.Color(164, 196, 181));
        ingresar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        ingresar.setText("Sign In");
        ingresar.setBorder(null);
        ingresar.setBorderPainted(false);
        ingresar.setContentAreaFilled(false);
        ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(User))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(User1))
                            .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1))
                                .addComponent(Separator, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(TitleEmpresa))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(NameEmpresa))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(ingresar)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton4)
                .addGap(15, 15, 15)
                .addComponent(NameEmpresa)
                .addGap(44, 44, 44)
                .addComponent(TitleEmpresa)
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(User1)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(User)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(ingresar)
                .addGap(46, 46, 46))
        );

        JPLogin.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 440, 500));

        BackGround.setBackground(new java.awt.Color(164, 196, 181));

        jLabel14.setFont(new java.awt.Font("Fira Code Light", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Exploring new");

        jLabel15.setFont(new java.awt.Font("Fira Code Light", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("horizons together");

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel14))
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel15))
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1004, Short.MAX_VALUE))
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        JPLogin.add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        JPPrincipal.setBackground(new java.awt.Color(204, 255, 204));
        JPPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPCabecera.setBackground(new java.awt.Color(255, 255, 255));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lista (1).png"))); // NOI18N
        jToggleButton1.setBorder(null);
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPCabeceraLayout = new javax.swing.GroupLayout(JPCabecera);
        JPCabecera.setLayout(JPCabeceraLayout);
        JPCabeceraLayout.setHorizontalGroup(
            JPCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(817, Short.MAX_VALUE))
        );
        JPCabeceraLayout.setVerticalGroup(
            JPCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        JPPrincipal.add(JPCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 60));

        JPMenu.setBackground(new java.awt.Color(255, 255, 255));
        JPMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPBienvenida.setBackground(new java.awt.Color(253, 233, 181));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout JPBienvenidaLayout = new javax.swing.GroupLayout(JPBienvenida);
        JPBienvenida.setLayout(JPBienvenidaLayout);
        JPBienvenidaLayout.setHorizontalGroup(
            JPBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBienvenidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPBienvenidaLayout.setVerticalGroup(
            JPBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPBienvenidaLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JPMenu.add(JPBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 210, -1));

        JPCajero.setBackground(new java.awt.Color(255, 255, 255));
        JPCajero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPBotonesCajero.setBackground(new java.awt.Color(255, 255, 255));

        btnPanelRegistrarCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/entrega-de-pedidos.png"))); // NOI18N
        btnPanelRegistrarCliente1.setBorder(null);
        btnPanelRegistrarCliente1.setBorderPainted(false);
        btnPanelRegistrarCliente1.setContentAreaFilled(false);
        btnPanelRegistrarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelRegistrarCliente1ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("INGRESAR PEDIDO");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("GENERAR FACTURA");

        btnPanelRegistrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        btnPanelRegistrarCliente.setBorder(null);
        btnPanelRegistrarCliente.setBorderPainted(false);
        btnPanelRegistrarCliente.setContentAreaFilled(false);
        btnPanelRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelRegistrarClienteActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("REGISTRAR CLIENTE");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("ELEGIR MESA");

        btnPanelRegistrarCliente3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuenta.png"))); // NOI18N
        btnPanelRegistrarCliente3.setBorder(null);
        btnPanelRegistrarCliente3.setBorderPainted(false);
        btnPanelRegistrarCliente3.setContentAreaFilled(false);
        btnPanelRegistrarCliente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelRegistrarCliente3ActionPerformed(evt);
            }
        });

        btnPanelRegistrarCliente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comedor.png"))); // NOI18N
        btnPanelRegistrarCliente2.setBorder(null);
        btnPanelRegistrarCliente2.setBorderPainted(false);
        btnPanelRegistrarCliente2.setContentAreaFilled(false);
        btnPanelRegistrarCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelRegistrarCliente2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPBotonesCajeroLayout = new javax.swing.GroupLayout(JPBotonesCajero);
        JPBotonesCajero.setLayout(JPBotonesCajeroLayout);
        JPBotonesCajeroLayout.setHorizontalGroup(
            JPBotonesCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBotonesCajeroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPBotonesCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPBotonesCajeroLayout.createSequentialGroup()
                        .addComponent(btnPanelRegistrarCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(JPBotonesCajeroLayout.createSequentialGroup()
                        .addComponent(btnPanelRegistrarCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(JPBotonesCajeroLayout.createSequentialGroup()
                        .addComponent(btnPanelRegistrarCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(JPBotonesCajeroLayout.createSequentialGroup()
                        .addComponent(btnPanelRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        JPBotonesCajeroLayout.setVerticalGroup(
            JPBotonesCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBotonesCajeroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPBotonesCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPBotonesCajeroLayout.createSequentialGroup()
                        .addComponent(btnPanelRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPBotonesCajeroLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(17, 17, 17)))
                .addGroup(JPBotonesCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPanelRegistrarCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPBotonesCajeroLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPBotonesCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPanelRegistrarCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPBotonesCajeroLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPBotonesCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPanelRegistrarCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPBotonesCajeroLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );

        JPCajero.add(JPBotonesCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        JPMenu.add(JPCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, 430));

        JPAdministrador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPanelRegistrarCliente5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/entrega-de-pedidos.png"))); // NOI18N
        btnPanelRegistrarCliente5.setBorder(null);
        btnPanelRegistrarCliente5.setBorderPainted(false);
        btnPanelRegistrarCliente5.setContentAreaFilled(false);
        btnPanelRegistrarCliente5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelRegistrarCliente5ActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setText("CONSULTAR INV.");

        btnPanelRegistrarCliente4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alquiler.png"))); // NOI18N
        btnPanelRegistrarCliente4.setBorder(null);
        btnPanelRegistrarCliente4.setBorderPainted(false);
        btnPanelRegistrarCliente4.setContentAreaFilled(false);
        btnPanelRegistrarCliente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelRegistrarCliente4ActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setText("AGREGAR PRODUCTO");

        btnPanelRegistrarCliente6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comedor.png"))); // NOI18N
        btnPanelRegistrarCliente6.setBorder(null);
        btnPanelRegistrarCliente6.setBorderPainted(false);
        btnPanelRegistrarCliente6.setContentAreaFilled(false);
        btnPanelRegistrarCliente6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelRegistrarCliente6ActionPerformed(evt);
            }
        });

        btnPanelRegistrarCliente7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuenta.png"))); // NOI18N
        btnPanelRegistrarCliente7.setBorder(null);
        btnPanelRegistrarCliente7.setBorderPainted(false);
        btnPanelRegistrarCliente7.setContentAreaFilled(false);
        btnPanelRegistrarCliente7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelRegistrarCliente7ActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setText("REGISTRAR EMPLEADO");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel10.setText("REALIZAR INFORME");

        javax.swing.GroupLayout JPBotonesAdminLayout = new javax.swing.GroupLayout(JPBotonesAdmin);
        JPBotonesAdmin.setLayout(JPBotonesAdminLayout);
        JPBotonesAdminLayout.setHorizontalGroup(
            JPBotonesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBotonesAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPBotonesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPBotonesAdminLayout.createSequentialGroup()
                        .addComponent(btnPanelRegistrarCliente7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(JPBotonesAdminLayout.createSequentialGroup()
                        .addComponent(btnPanelRegistrarCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(JPBotonesAdminLayout.createSequentialGroup()
                        .addComponent(btnPanelRegistrarCliente5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(JPBotonesAdminLayout.createSequentialGroup()
                        .addComponent(btnPanelRegistrarCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );
        JPBotonesAdminLayout.setVerticalGroup(
            JPBotonesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBotonesAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPBotonesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPBotonesAdminLayout.createSequentialGroup()
                        .addComponent(btnPanelRegistrarCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPBotonesAdminLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(17, 17, 17)))
                .addGroup(JPBotonesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPanelRegistrarCliente5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPBotonesAdminLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPBotonesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPanelRegistrarCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPBotonesAdminLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPBotonesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPanelRegistrarCliente7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPBotonesAdminLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel10)))
                .addContainerGap())
        );

        JPAdministrador.add(JPBotonesAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 46, -1, -1));

        JPMenu.add(JPAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, 430));

        JPPrincipal.add(JPMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 210, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(JPLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                    .addGap(35, 35, 35)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(JPLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(35, 35, 35)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        int position = this.JPMenu.getX();
        if(position > -1){
            Animacion.Animacion.mover_izquierda(0, -220, 2, 2, JPMenu);
        }else{
            Animacion.Animacion.mover_derecha(-220, 0, 2, 2, JPMenu);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btnPanelRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelRegistrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPanelRegistrarClienteActionPerformed

    private void btnPanelRegistrarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelRegistrarCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPanelRegistrarCliente1ActionPerformed

    private void btnPanelRegistrarCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelRegistrarCliente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPanelRegistrarCliente2ActionPerformed

    private void btnPanelRegistrarCliente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelRegistrarCliente3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPanelRegistrarCliente3ActionPerformed

    private void btnPanelRegistrarCliente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelRegistrarCliente4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPanelRegistrarCliente4ActionPerformed

    private void btnPanelRegistrarCliente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelRegistrarCliente5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPanelRegistrarCliente5ActionPerformed

    private void btnPanelRegistrarCliente6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelRegistrarCliente6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPanelRegistrarCliente6ActionPerformed

    private void btnPanelRegistrarCliente7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelRegistrarCliente7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPanelRegistrarCliente7ActionPerformed

    private void UsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuarioMousePressed
        if(Usuario.getText().equals("Ingrese su usuario")){
            Usuario.setText("");
            Usuario.setForeground(Color.black);
        }

        if (String.valueOf(Pass.getPassword()).isEmpty()) {
            Pass.setText("**********");
            Pass.setForeground(Color.gray);
        }
    }//GEN-LAST:event_UsuarioMousePressed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
        Pass.requestFocus();

    }//GEN-LAST:event_UsuarioActionPerformed

    private void PassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassMousePressed
        if(String.valueOf(Pass.getPassword()).equals("**********")) {
            Pass.setText("");
            Pass.setForeground(Color.black);
        }
        if(Usuario.getText().isEmpty()){
            Usuario.setText("Ingrese su usuario");
            Usuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_PassMousePressed

    private void PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_PassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDashboard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDashboard2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel JPAdministrador;
    private javax.swing.JPanel JPBienvenida;
    private javax.swing.JPanel JPBotonesAdmin;
    private javax.swing.JPanel JPBotonesCajero;
    private javax.swing.JPanel JPCabecera;
    private javax.swing.JPanel JPCajero;
    private javax.swing.JPanel JPLogin;
    private javax.swing.JPanel JPMenu;
    private javax.swing.JPanel JPPrincipal;
    private javax.swing.JLabel NameEmpresa;
    public javax.swing.JPasswordField Pass;
    private javax.swing.JSeparator Separator;
    private javax.swing.JSeparator Separator1;
    private javax.swing.JLabel TitleEmpresa;
    private javax.swing.JLabel User;
    private javax.swing.JLabel User1;
    public javax.swing.JTextField Usuario;
    private javax.swing.JToggleButton btnPanelRegistrarCliente;
    private javax.swing.JToggleButton btnPanelRegistrarCliente1;
    private javax.swing.JToggleButton btnPanelRegistrarCliente2;
    private javax.swing.JToggleButton btnPanelRegistrarCliente3;
    private javax.swing.JToggleButton btnPanelRegistrarCliente4;
    private javax.swing.JToggleButton btnPanelRegistrarCliente5;
    private javax.swing.JToggleButton btnPanelRegistrarCliente6;
    private javax.swing.JToggleButton btnPanelRegistrarCliente7;
    private java.awt.Checkbox checkbox1;
    public javax.swing.JButton ingresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
