/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author ladje
 */
public class Ventanas extends javax.swing.JFrame {

    /**
     * Creates new form Ventanas
     */
    public Ventanas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaMesas = new javax.swing.JInternalFrame();
        comboTiposM = new javax.swing.JComboBox<>();
        btnOcuparMesa = new javax.swing.JButton();
        MesaCod = new javax.swing.JTextField();
        TituloMesa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        VentanaRegistroE = new javax.swing.JInternalFrame();
        lblNombreC1 = new javax.swing.JLabel();
        lblApellidoC1 = new javax.swing.JLabel();
        lblCedulaC1 = new javax.swing.JLabel();
        lblTelefonoC1 = new javax.swing.JLabel();
        lblDireccionC1 = new javax.swing.JLabel();
        Separator5 = new javax.swing.JSeparator();
        Separator6 = new javax.swing.JSeparator();
        Separator7 = new javax.swing.JSeparator();
        Separator8 = new javax.swing.JSeparator();
        Separator9 = new javax.swing.JSeparator();
        txtNombreE = new javax.swing.JTextField();
        txtTelefonoE = new javax.swing.JTextField();
        txtCedulaE = new javax.swing.JTextField();
        txtUsuarioE = new javax.swing.JTextField();
        ValidacionUE = new javax.swing.JLabel();
        ValidacionCE = new javax.swing.JLabel();
        btnRegistrarEmpleado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtContraseñaE = new javax.swing.JPasswordField();
        comboRoles = new javax.swing.JComboBox<>();
        lblDireccionC2 = new javax.swing.JLabel();
        lblNombreC2 = new javax.swing.JLabel();
        txtApellidoE = new javax.swing.JTextField();
        Separator10 = new javax.swing.JSeparator();
        ValidacionTE1 = new javax.swing.JLabel();
        VentanaRegistrarC = new javax.swing.JInternalFrame();
        lblNombreC = new javax.swing.JLabel();
        lblApellidoC = new javax.swing.JLabel();
        lblCedulaC = new javax.swing.JLabel();
        lblTelefonoC = new javax.swing.JLabel();
        lblDireccionC = new javax.swing.JLabel();
        Separator = new javax.swing.JSeparator();
        Separator1 = new javax.swing.JSeparator();
        Separator2 = new javax.swing.JSeparator();
        Separator3 = new javax.swing.JSeparator();
        Separator4 = new javax.swing.JSeparator();
        txtNombreC = new javax.swing.JTextField();
        txtApellidoC = new javax.swing.JTextField();
        txtDireccionC = new javax.swing.JTextField();
        txtCedulaC = new javax.swing.JTextField();
        txtTelefonoC = new javax.swing.JTextField();
        ValidacionT = new javax.swing.JLabel();
        ValidacionC = new javax.swing.JLabel();
        btnRegistrarCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        VentanaPedidos = new javax.swing.JInternalFrame();
        VentanaGenerarF = new javax.swing.JInternalFrame();
        TituloFactura = new javax.swing.JLabel();
        comboCajeros = new javax.swing.JComboBox<>();
        comboTipoP = new javax.swing.JComboBox<>();
        comboMeseros = new javax.swing.JComboBox<>();
        txtCliente = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        btnGenerarFactura = new javax.swing.JButton();
        lblCajeros = new javax.swing.JLabel();
        lblMeseros = new javax.swing.JLabel();
        lblTipoP = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblDescuento = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        comboMesasO = new javax.swing.JComboBox<>();
        lblMesas = new javax.swing.JLabel();
        VentanaCrearM = new javax.swing.JInternalFrame();
        comboTipos = new javax.swing.JComboBox<>();
        txtCantidadS = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        btnCrearMesa = new javax.swing.JButton();
        lblTipoP1 = new javax.swing.JLabel();
        lblDescuento1 = new javax.swing.JLabel();
        lblDescuento2 = new javax.swing.JLabel();
        lblDescuento3 = new javax.swing.JLabel();
        VentanaAgregarP = new javax.swing.JInternalFrame();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        VentanaMostrarI = new javax.swing.JInternalFrame();
        jtffechainicio = new javax.swing.JTextField();
        jtffechafinal = new javax.swing.JTextField();
        jtfingredienteaconsulta = new javax.swing.JTextField();
        btconsultarinventario = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblsalidainvetario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VentanaMesas.setVisible(true);

        btnOcuparMesa.setText("Ocupar");

        MesaCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesaCodActionPerformed(evt);
            }
        });

        TituloMesa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloMesa.setText("Elegir Mesa");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout VentanaMesasLayout = new javax.swing.GroupLayout(VentanaMesas.getContentPane());
        VentanaMesas.getContentPane().setLayout(VentanaMesasLayout);
        VentanaMesasLayout.setHorizontalGroup(
            VentanaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaMesasLayout.createSequentialGroup()
                .addGroup(VentanaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaMesasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TituloMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(VentanaMesasLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(VentanaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MesaCod, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboTiposM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOcuparMesa))
                        .addGap(0, 53, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        VentanaMesasLayout.setVerticalGroup(
            VentanaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaMesasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboTiposM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MesaCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOcuparMesa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaMesasLayout.createSequentialGroup()
                .addGap(0, 371, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        VentanaRegistroE.setMaximumSize(new java.awt.Dimension(570, 470));
        VentanaRegistroE.setPreferredSize(new java.awt.Dimension(570, 470));
        VentanaRegistroE.setVisible(true);

        lblNombreC1.setFont(new java.awt.Font("Fira Code", 1, 16)); // NOI18N
        lblNombreC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UsuarioN.png"))); // NOI18N
        lblNombreC1.setText("Nombre");

        lblApellidoC1.setFont(new java.awt.Font("Fira Code", 1, 16)); // NOI18N
        lblApellidoC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/telefono.png"))); // NOI18N
        lblApellidoC1.setText("Teléfono");

        lblCedulaC1.setFont(new java.awt.Font("Fira Code", 1, 16)); // NOI18N
        lblCedulaC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        lblCedulaC1.setText("Cédula");

        lblTelefonoC1.setFont(new java.awt.Font("Fira Code", 1, 16)); // NOI18N
        lblTelefonoC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UsuarioA.png"))); // NOI18N
        lblTelefonoC1.setText("Usuario");

        lblDireccionC1.setFont(new java.awt.Font("Fira Code", 1, 16)); // NOI18N
        lblDireccionC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contrasena.png"))); // NOI18N
        lblDireccionC1.setText("Contraseña");

        txtNombreE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombreE.setForeground(new java.awt.Color(204, 204, 204));
        txtNombreE.setText("Ingrese su Nombre");
        txtNombreE.setToolTipText("");
        txtNombreE.setActionCommand("<Not Set>");
        txtNombreE.setBorder(null);
        txtNombreE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreEMousePressed(evt);
            }
        });
        txtNombreE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEActionPerformed(evt);
            }
        });

        txtTelefonoE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTelefonoE.setForeground(new java.awt.Color(204, 204, 204));
        txtTelefonoE.setText("Inrgese su Teléfono");
        txtTelefonoE.setToolTipText("");
        txtTelefonoE.setActionCommand("<Not Set>");
        txtTelefonoE.setBorder(null);
        txtTelefonoE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoEMousePressed(evt);
            }
        });
        txtTelefonoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoEActionPerformed(evt);
            }
        });

        txtCedulaE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCedulaE.setForeground(new java.awt.Color(204, 204, 204));
        txtCedulaE.setText("Ingrese su Cédula");
        txtCedulaE.setToolTipText("");
        txtCedulaE.setActionCommand("<Not Set>");
        txtCedulaE.setBorder(null);
        txtCedulaE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedulaEMousePressed(evt);
            }
        });
        txtCedulaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaEActionPerformed(evt);
            }
        });

        txtUsuarioE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsuarioE.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuarioE.setText("Ingrese su Usuario");
        txtUsuarioE.setToolTipText("");
        txtUsuarioE.setActionCommand("<Not Set>");
        txtUsuarioE.setBorder(null);
        txtUsuarioE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioEMousePressed(evt);
            }
        });
        txtUsuarioE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioEActionPerformed(evt);
            }
        });

        ValidacionUE.setText("jLabel1");

        ValidacionCE.setText("jLabel1");

        btnRegistrarEmpleado.setText("Registrar Empleado");
        btnRegistrarEmpleado.setBorder(null);
        btnRegistrarEmpleado.setBorderPainted(false);
        btnRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEmpleadoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Registrar Empleado");

        txtContraseñaE.setForeground(new java.awt.Color(204, 204, 204));
        txtContraseñaE.setText("jPasswordField1");
        txtContraseñaE.setBorder(null);

        lblDireccionC2.setFont(new java.awt.Font("Fira Code", 1, 16)); // NOI18N
        lblDireccionC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/roles.png"))); // NOI18N
        lblDireccionC2.setText("Rol");

        lblNombreC2.setFont(new java.awt.Font("Fira Code", 1, 16)); // NOI18N
        lblNombreC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UsuarioN.png"))); // NOI18N
        lblNombreC2.setText("Apellido");

        txtApellidoE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellidoE.setForeground(new java.awt.Color(204, 204, 204));
        txtApellidoE.setText("Ingrese su Apellido");
        txtApellidoE.setToolTipText("");
        txtApellidoE.setActionCommand("<Not Set>");
        txtApellidoE.setBorder(null);
        txtApellidoE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoEMousePressed(evt);
            }
        });
        txtApellidoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoEActionPerformed(evt);
            }
        });

        ValidacionTE1.setText("jLabel1");

        javax.swing.GroupLayout VentanaRegistroELayout = new javax.swing.GroupLayout(VentanaRegistroE.getContentPane());
        VentanaRegistroE.getContentPane().setLayout(VentanaRegistroELayout);
        VentanaRegistroELayout.setHorizontalGroup(
            VentanaRegistroELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaRegistroELayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(VentanaRegistroELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaRegistroELayout.createSequentialGroup()
                        .addComponent(ValidacionTE1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(VentanaRegistroELayout.createSequentialGroup()
                        .addGroup(VentanaRegistroELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VentanaRegistroELayout.createSequentialGroup()
                                .addGroup(VentanaRegistroELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(VentanaRegistroELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblCedulaC1)
                                        .addComponent(lblApellidoC1)
                                        .addComponent(txtTelefonoE)
                                        .addComponent(Separator6, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(VentanaRegistroELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCedulaE, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Separator7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(VentanaRegistroELayout.createSequentialGroup()
                                        .addGroup(VentanaRegistroELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblNombreC1)
                                            .addComponent(Separator5)
                                            .addComponent(txtNombreE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(VentanaRegistroELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblNombreC2)
                                            .addComponent(Separator10)
                                            .addComponent(txtApellidoE, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))))
                                .addGap(34, 34, 34)
                                .addGroup(VentanaRegistroELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTelefonoC1)
                                    .addComponent(lblDireccionC1)
                                    .addComponent(txtUsuarioE, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Separator8, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(VentanaRegistroELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtContraseñaE, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Separator9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblDireccionC2)
                                    .addComponent(comboRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ValidacionUE)))
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(VentanaRegistroELayout.createSequentialGroup()
                        .addComponent(ValidacionCE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrarEmpleado)
                        .addGap(54, 54, 54))))
        );
        VentanaRegistroELayout.setVerticalGroup(
            VentanaRegistroELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaRegistroELayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VentanaRegistroELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaRegistroELayout.createSequentialGroup()
                        .addGroup(VentanaRegistroELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreC1)
                            .addComponent(lblTelefonoC1))
                        .addGap(7, 7, 7)
                        .addGroup(VentanaRegistroELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuarioE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(VentanaRegistroELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Separator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Separator5, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(VentanaRegistroELayout.createSequentialGroup()
                        .addComponent(lblNombreC2)
                        .addGap(7, 7, 7)
                        .addComponent(txtApellidoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Separator10, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ValidacionUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VentanaRegistroELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaRegistroELayout.createSequentialGroup()
                        .addGroup(VentanaRegistroELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidoC1)
                            .addComponent(lblDireccionC1))
                        .addGap(15, 15, 15)
                        .addGroup(VentanaRegistroELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefonoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContraseñaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Separator6, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Separator8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(ValidacionTE1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaRegistroELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedulaC1)
                    .addComponent(lblDireccionC2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VentanaRegistroELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedulaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(Separator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VentanaRegistroELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ValidacionCE)
                    .addComponent(btnRegistrarEmpleado))
                .addGap(60, 60, 60))
        );

        VentanaRegistrarC.setMaximumSize(new java.awt.Dimension(570, 470));
        VentanaRegistrarC.setPreferredSize(new java.awt.Dimension(570, 470));
        VentanaRegistrarC.setVisible(true);

        lblNombreC.setFont(new java.awt.Font("Fira Code", 1, 16)); // NOI18N
        lblNombreC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UsuarioN.png"))); // NOI18N
        lblNombreC.setText("Nombre");

        lblApellidoC.setFont(new java.awt.Font("Fira Code", 1, 16)); // NOI18N
        lblApellidoC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UsuarioA.png"))); // NOI18N
        lblApellidoC.setText("Apellido");

        lblCedulaC.setFont(new java.awt.Font("Fira Code", 1, 16)); // NOI18N
        lblCedulaC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ID.png"))); // NOI18N
        lblCedulaC.setText("Cédula");

        lblTelefonoC.setFont(new java.awt.Font("Fira Code", 1, 16)); // NOI18N
        lblTelefonoC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/telefono.png"))); // NOI18N
        lblTelefonoC.setText("Teléfono");

        lblDireccionC.setFont(new java.awt.Font("Fira Code", 1, 16)); // NOI18N
        lblDireccionC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Direccion.png"))); // NOI18N
        lblDireccionC.setText("Dirección");

        txtNombreC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombreC.setForeground(new java.awt.Color(204, 204, 204));
        txtNombreC.setText("Ingrese su Nombre");
        txtNombreC.setToolTipText("");
        txtNombreC.setActionCommand("<Not Set>");
        txtNombreC.setBorder(null);
        txtNombreC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreCMousePressed(evt);
            }
        });
        txtNombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCActionPerformed(evt);
            }
        });

        txtApellidoC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellidoC.setForeground(new java.awt.Color(204, 204, 204));
        txtApellidoC.setText("Inrgese su Apellido");
        txtApellidoC.setToolTipText("");
        txtApellidoC.setActionCommand("<Not Set>");
        txtApellidoC.setBorder(null);
        txtApellidoC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoCMousePressed(evt);
            }
        });
        txtApellidoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoCActionPerformed(evt);
            }
        });

        txtDireccionC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDireccionC.setForeground(new java.awt.Color(204, 204, 204));
        txtDireccionC.setText("Ingrese su Dirección");
        txtDireccionC.setToolTipText("");
        txtDireccionC.setActionCommand("<Not Set>");
        txtDireccionC.setBorder(null);
        txtDireccionC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDireccionCMousePressed(evt);
            }
        });
        txtDireccionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionCActionPerformed(evt);
            }
        });

        txtCedulaC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCedulaC.setForeground(new java.awt.Color(204, 204, 204));
        txtCedulaC.setText("Ingrese su Cédula");
        txtCedulaC.setToolTipText("");
        txtCedulaC.setActionCommand("<Not Set>");
        txtCedulaC.setBorder(null);
        txtCedulaC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedulaCMousePressed(evt);
            }
        });
        txtCedulaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaCActionPerformed(evt);
            }
        });

        txtTelefonoC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTelefonoC.setForeground(new java.awt.Color(204, 204, 204));
        txtTelefonoC.setText("Ingrese su Teléfono");
        txtTelefonoC.setToolTipText("");
        txtTelefonoC.setActionCommand("<Not Set>");
        txtTelefonoC.setBorder(null);
        txtTelefonoC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoCMousePressed(evt);
            }
        });
        txtTelefonoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoCActionPerformed(evt);
            }
        });

        ValidacionT.setText("jLabel1");

        ValidacionC.setText("jLabel1");

        btnRegistrarCliente.setText("Registrar Cliente");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Registrar Cliente");

        javax.swing.GroupLayout VentanaRegistrarCLayout = new javax.swing.GroupLayout(VentanaRegistrarC.getContentPane());
        VentanaRegistrarC.getContentPane().setLayout(VentanaRegistrarCLayout);
        VentanaRegistrarCLayout.setHorizontalGroup(
            VentanaRegistrarCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaRegistrarCLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(VentanaRegistrarCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(ValidacionC)
                    .addGroup(VentanaRegistrarCLayout.createSequentialGroup()
                        .addGroup(VentanaRegistrarCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VentanaRegistrarCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblCedulaC)
                                .addComponent(lblNombreC)
                                .addComponent(lblApellidoC)
                                .addComponent(txtApellidoC)
                                .addComponent(txtNombreC, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                .addComponent(Separator)
                                .addComponent(Separator1))
                            .addGroup(VentanaRegistrarCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCedulaC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addComponent(Separator2, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(76, 76, 76)
                        .addGroup(VentanaRegistrarCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ValidacionT)
                            .addGroup(VentanaRegistrarCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDireccionC, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                .addComponent(lblTelefonoC)
                                .addComponent(lblDireccionC)
                                .addComponent(txtTelefonoC, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Separator4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Separator3))
                            .addGroup(VentanaRegistrarCLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnRegistrarCliente)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VentanaRegistrarCLayout.setVerticalGroup(
            VentanaRegistrarCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaRegistrarCLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(91, 91, 91)
                .addGroup(VentanaRegistrarCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreC)
                    .addComponent(lblTelefonoC))
                .addGap(7, 7, 7)
                .addGroup(VentanaRegistrarCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaRegistrarCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Separator4)
                    .addComponent(Separator))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ValidacionT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(VentanaRegistrarCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaRegistrarCLayout.createSequentialGroup()
                        .addGroup(VentanaRegistrarCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidoC)
                            .addComponent(lblDireccionC))
                        .addGap(15, 15, 15)
                        .addGroup(VentanaRegistrarCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccionC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Separator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(lblCedulaC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VentanaRegistrarCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedulaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarCliente))
                .addGap(5, 5, 5)
                .addComponent(Separator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ValidacionC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        VentanaPedidos.setVisible(true);

        javax.swing.GroupLayout VentanaPedidosLayout = new javax.swing.GroupLayout(VentanaPedidos.getContentPane());
        VentanaPedidos.getContentPane().setLayout(VentanaPedidosLayout);
        VentanaPedidosLayout.setHorizontalGroup(
            VentanaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        VentanaPedidosLayout.setVerticalGroup(
            VentanaPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 875, Short.MAX_VALUE)
        );

        VentanaGenerarF.setVisible(true);

        TituloFactura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloFactura.setText("Generar Factura");

        comboCajeros.setBorder(null);

        comboTipoP.setBorder(null);

        comboMeseros.setBorder(null);

        txtCliente.setForeground(new java.awt.Color(204, 204, 204));
        txtCliente.setText("Ingresar ID");
        txtCliente.setBorder(null);

        txtDesc.setForeground(new java.awt.Color(204, 204, 204));
        txtDesc.setText("Ingresar Desc");
        txtDesc.setBorder(null);

        btnGenerarFactura.setText("Generar Factura");
        btnGenerarFactura.setBorder(null);
        btnGenerarFactura.setBorderPainted(false);

        lblCajeros.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCajeros.setText("Cajeros");

        lblMeseros.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblMeseros.setText("Meseros");

        lblTipoP.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTipoP.setText("Tipo Pago");

        lblCliente.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCliente.setText("Cliente ID");

        lblDescuento.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDescuento.setText("Descuento");

        comboMesasO.setBorder(null);

        lblMesas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblMesas.setText("Mesas");

        javax.swing.GroupLayout VentanaGenerarFLayout = new javax.swing.GroupLayout(VentanaGenerarF.getContentPane());
        VentanaGenerarF.getContentPane().setLayout(VentanaGenerarFLayout);
        VentanaGenerarFLayout.setHorizontalGroup(
            VentanaGenerarFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaGenerarFLayout.createSequentialGroup()
                .addGroup(VentanaGenerarFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaGenerarFLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(VentanaGenerarFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VentanaGenerarFLayout.createSequentialGroup()
                                .addGroup(VentanaGenerarFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboCajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCliente)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(VentanaGenerarFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDescuento)
                                    .addGroup(VentanaGenerarFLayout.createSequentialGroup()
                                        .addGroup(VentanaGenerarFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboTipoP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTipoP)
                                            .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addGroup(VentanaGenerarFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnGenerarFactura)
                                            .addGroup(VentanaGenerarFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(comboMeseros, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblMeseros, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                        .addGroup(VentanaGenerarFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comboMesasO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(26, 26, 26))
                            .addComponent(TituloFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(VentanaGenerarFLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        VentanaGenerarFLayout.setVerticalGroup(
            VentanaGenerarFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaGenerarFLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(TituloFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(VentanaGenerarFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCajeros)
                    .addComponent(lblMeseros)
                    .addComponent(lblTipoP)
                    .addComponent(lblMesas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaGenerarFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTipoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMeseros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMesasO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(VentanaGenerarFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(lblDescuento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaGenerarFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarFactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaGenerarFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2))
                .addContainerGap(504, Short.MAX_VALUE))
        );

        VentanaCrearM.setVisible(true);

        comboTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Familiar", "Individual", "Grupal", "Pareja", "Esquina", "Buffet", "Comunal" }));
        comboTipos.setBorder(null);

        txtCantidadS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidadS.setText("Cantidad");
        txtCantidadS.setBorder(null);

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Estado");
        jTextField2.setBorder(null);

        btnCrearMesa.setText("Crear Mesa");

        lblTipoP1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTipoP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipoP1.setText("Crear Mesa");

        lblDescuento1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDescuento1.setText("Tipo Mesa");

        lblDescuento2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDescuento2.setText("Estado Mesa");

        lblDescuento3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDescuento3.setText("Cantidad Sillas");

        javax.swing.GroupLayout VentanaCrearMLayout = new javax.swing.GroupLayout(VentanaCrearM.getContentPane());
        VentanaCrearM.getContentPane().setLayout(VentanaCrearMLayout);
        VentanaCrearMLayout.setHorizontalGroup(
            VentanaCrearMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaCrearMLayout.createSequentialGroup()
                .addGroup(VentanaCrearMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCrearMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(VentanaCrearMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(VentanaCrearMLayout.createSequentialGroup()
                            .addGap(86, 86, 86)
                            .addComponent(lblTipoP1))
                        .addGroup(VentanaCrearMLayout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(VentanaCrearMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDescuento1)
                                .addComponent(txtCantidadS, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDescuento2)
                                .addComponent(lblDescuento3)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        VentanaCrearMLayout.setVerticalGroup(
            VentanaCrearMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaCrearMLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTipoP1)
                .addGap(20, 20, 20)
                .addComponent(lblDescuento1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDescuento3)
                .addGap(2, 2, 2)
                .addComponent(txtCantidadS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(lblDescuento2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCrearMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(356, Short.MAX_VALUE))
        );

        VentanaAgregarP.setVisible(true);

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField1.setText("jTextField1");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "Title 6"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout VentanaAgregarPLayout = new javax.swing.GroupLayout(VentanaAgregarP.getContentPane());
        VentanaAgregarP.getContentPane().setLayout(VentanaAgregarPLayout);
        VentanaAgregarPLayout.setHorizontalGroup(
            VentanaAgregarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaAgregarPLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addGap(31, 31, 31)
                .addGroup(VentanaAgregarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addGroup(VentanaAgregarPLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(41, 41, 41)
                        .addComponent(jButton3))
                    .addGroup(VentanaAgregarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        VentanaAgregarPLayout.setVerticalGroup(
            VentanaAgregarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaAgregarPLayout.createSequentialGroup()
                .addGroup(VentanaAgregarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(VentanaAgregarPLayout.createSequentialGroup()
                        .addContainerGap(359, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VentanaAgregarPLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(VentanaAgregarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addGap(31, 31, 31))
        );

        VentanaMostrarI.setVisible(true);

        jtffechainicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtffechainicioActionPerformed(evt);
            }
        });

        btconsultarinventario.setText("Consultar");

        jButton6.setText("Exportar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jtblsalidainvetario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblsalidainvetario.setColumnSelectionAllowed(true);
        jtblsalidainvetario.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jtblsalidainvetario);
        jtblsalidainvetario.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jtblsalidainvetario.getColumnModel().getColumnCount() > 0) {
            jtblsalidainvetario.getColumnModel().getColumn(0).setResizable(false);
            jtblsalidainvetario.getColumnModel().getColumn(1).setResizable(false);
            jtblsalidainvetario.getColumnModel().getColumn(2).setResizable(false);
            jtblsalidainvetario.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout VentanaMostrarILayout = new javax.swing.GroupLayout(VentanaMostrarI.getContentPane());
        VentanaMostrarI.getContentPane().setLayout(VentanaMostrarILayout);
        VentanaMostrarILayout.setHorizontalGroup(
            VentanaMostrarILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaMostrarILayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(VentanaMostrarILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaMostrarILayout.createSequentialGroup()
                        .addComponent(jtfingredienteaconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VentanaMostrarILayout.createSequentialGroup()
                        .addGroup(VentanaMostrarILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtffechainicio, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtffechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btconsultarinventario)))
                .addGap(211, 211, 211))
            .addGroup(VentanaMostrarILayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VentanaMostrarILayout.setVerticalGroup(
            VentanaMostrarILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaMostrarILayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(VentanaMostrarILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtffechainicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btconsultarinventario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaMostrarILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(VentanaMostrarILayout.createSequentialGroup()
                        .addComponent(jtffechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfingredienteaconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VentanaMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(VentanaMostrarI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VentanaRegistroE, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(VentanaRegistrarC, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(VentanaPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VentanaGenerarF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(VentanaAgregarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VentanaCrearM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VentanaAgregarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(VentanaRegistrarC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(VentanaPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(569, 569, 569))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(VentanaRegistroE, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(599, 599, 599))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(VentanaMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(VentanaMostrarI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VentanaGenerarF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(VentanaCrearM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreEMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEMousePressed

    private void txtNombreEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEActionPerformed

    private void txtTelefonoEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoEMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoEMousePressed

    private void txtTelefonoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoEActionPerformed

    private void txtCedulaEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaEMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaEMousePressed

    private void txtCedulaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaEActionPerformed

    private void txtUsuarioEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioEMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioEMousePressed

    private void txtUsuarioEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioEActionPerformed

    private void btnRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarEmpleadoActionPerformed

    private void txtApellidoEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoEMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoEMousePressed

    private void txtApellidoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoEActionPerformed

    private void txtNombreCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreCMousePressed

    }//GEN-LAST:event_txtNombreCMousePressed

    private void txtNombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCActionPerformed

    }//GEN-LAST:event_txtNombreCActionPerformed

    private void txtApellidoCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoCMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoCMousePressed

    private void txtApellidoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoCActionPerformed

    private void txtDireccionCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDireccionCMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionCMousePressed

    private void txtDireccionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionCActionPerformed

    private void txtCedulaCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaCMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaCMousePressed

    private void txtCedulaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaCActionPerformed

    private void txtTelefonoCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoCMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoCMousePressed

    private void txtTelefonoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoCActionPerformed

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void jtffechainicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtffechainicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtffechainicioActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void MesaCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MesaCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MesaCodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventanas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MesaCod;
    private javax.swing.JSeparator Separator;
    private javax.swing.JSeparator Separator1;
    private javax.swing.JSeparator Separator10;
    private javax.swing.JSeparator Separator2;
    private javax.swing.JSeparator Separator3;
    private javax.swing.JSeparator Separator4;
    private javax.swing.JSeparator Separator5;
    private javax.swing.JSeparator Separator6;
    private javax.swing.JSeparator Separator7;
    private javax.swing.JSeparator Separator8;
    private javax.swing.JSeparator Separator9;
    private javax.swing.JLabel TituloFactura;
    private javax.swing.JLabel TituloMesa;
    public javax.swing.JLabel ValidacionC;
    public javax.swing.JLabel ValidacionCE;
    public javax.swing.JLabel ValidacionT;
    public javax.swing.JLabel ValidacionTE1;
    public javax.swing.JLabel ValidacionUE;
    public javax.swing.JInternalFrame VentanaAgregarP;
    public javax.swing.JInternalFrame VentanaCrearM;
    public javax.swing.JInternalFrame VentanaGenerarF;
    public javax.swing.JInternalFrame VentanaMesas;
    public javax.swing.JInternalFrame VentanaMostrarI;
    public javax.swing.JInternalFrame VentanaPedidos;
    public javax.swing.JInternalFrame VentanaRegistrarC;
    public javax.swing.JInternalFrame VentanaRegistroE;
    public javax.swing.JButton btconsultarinventario;
    public javax.swing.JButton btnCrearMesa;
    public javax.swing.JButton btnGenerarFactura;
    private javax.swing.JButton btnOcuparMesa;
    public javax.swing.JButton btnRegistrarCliente;
    public javax.swing.JButton btnRegistrarEmpleado;
    public javax.swing.JComboBox<String> comboCajeros;
    public javax.swing.JComboBox<String> comboMesasO;
    public javax.swing.JComboBox<String> comboMeseros;
    public javax.swing.JComboBox<String> comboRoles;
    public javax.swing.JComboBox<String> comboTipoP;
    public javax.swing.JComboBox<String> comboTipos;
    private javax.swing.JComboBox<String> comboTiposM;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    public javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTable jtblsalidainvetario;
    public javax.swing.JTextField jtffechafinal;
    public javax.swing.JTextField jtffechainicio;
    public javax.swing.JTextField jtfingredienteaconsulta;
    private javax.swing.JLabel lblApellidoC;
    private javax.swing.JLabel lblApellidoC1;
    private javax.swing.JLabel lblCajeros;
    private javax.swing.JLabel lblCedulaC;
    private javax.swing.JLabel lblCedulaC1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblDescuento1;
    private javax.swing.JLabel lblDescuento2;
    private javax.swing.JLabel lblDescuento3;
    private javax.swing.JLabel lblDireccionC;
    private javax.swing.JLabel lblDireccionC1;
    private javax.swing.JLabel lblDireccionC2;
    private javax.swing.JLabel lblMesas;
    private javax.swing.JLabel lblMeseros;
    private javax.swing.JLabel lblNombreC;
    private javax.swing.JLabel lblNombreC1;
    private javax.swing.JLabel lblNombreC2;
    private javax.swing.JLabel lblTelefonoC;
    private javax.swing.JLabel lblTelefonoC1;
    private javax.swing.JLabel lblTipoP;
    private javax.swing.JLabel lblTipoP1;
    public javax.swing.JTextField txtApellidoC;
    public javax.swing.JTextField txtApellidoE;
    public javax.swing.JTextField txtCantidadS;
    public javax.swing.JTextField txtCedulaC;
    public javax.swing.JTextField txtCedulaE;
    public javax.swing.JTextField txtCliente;
    public javax.swing.JPasswordField txtContraseñaE;
    public javax.swing.JTextField txtDesc;
    public javax.swing.JTextField txtDireccionC;
    public javax.swing.JTextField txtNombreC;
    public javax.swing.JTextField txtNombreE;
    public javax.swing.JTextField txtTelefonoC;
    public javax.swing.JTextField txtTelefonoE;
    public javax.swing.JTextField txtUsuarioE;
    // End of variables declaration//GEN-END:variables
}
